# Generated by Django 4.0 on 2022-08-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_myvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myvideo',
            old_name='image_link',
            new_name='video_link',
        ),
        migrations.AlterField(
            model_name='myphoto',
            name='image_link',
            field=models.ImageField(null=True, upload_to='myphoto/'),
        ),
    ]
